# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
src/definitions.yaml:
  no-server-example.com:
    - "#/servers/3/url"
  tag-description:
    - "#/tags/0/description"
    - "#/tags/1/description"
    - "#/tags/2/description"
    - "#/tags/3/description"
    - "#/tags/4/description"
    - "#/tags/5/description"
    - "#/tags/6/description"
    - "#/tags/7/description"
    - "#/tags/8/description"
    - "#/tags/9/description"
    - "#/tags/10/description"
    - "#/tags/11/description"
    - "#/tags/12/description"
    - "#/tags/13/description"
    - "#/tags/14/description"
    - "#/tags/15/description"
    - "#/tags/16/description"
    - "#/tags/17/description"
  no-ambiguous-paths:
    - "#/paths/~1blocks~1slot~1{slot_number}"
    - "#/paths/~1blocks~1{hash_or_number}~1txs"
    - "#/paths/~1blocks~1{hash_or_number}~1addresses"
    - "#/paths/~1assets~1policy~1{policy_id}"
    - "#/paths/~1scripts~1datum~1{datum_hash}"
    - "#/paths/~1nutlink~1tickers~1{ticker}"
src/paths/api/root/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/health/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/health/clock.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/latest/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/latest/txs.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/{hash_or_number}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/{hash_or_number}/next.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/{hash_or_number}/previous.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/slot/{slot_number}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/epoch/{epoch_number}/slot/{slot_number}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/txs/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/blocks/addresses/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/genesis/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/latest/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/latest/parameters.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/next.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/previous.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/stakes.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/stakes/{pool_id}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/blocks/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/{pool_id}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/epochs/{number}/parameters.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/utxos.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/stakes.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/delegations.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/withdrawals.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/mirs.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/pool_updates.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/pool_retires.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/metadata/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/metadata/cbor.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/txs/{hash}/redeemers.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/tx/submit.yaml:
  operation-operationId:
    - "#/post/operationId"
src/paths/api/accounts/{stake_address}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/rewards.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/history.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/delegations.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/registrations.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/withdrawals.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/mirs.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/addresses.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/assets/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/accounts/{stake_address}/addresses/total.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/mempool/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/mempool/{hash}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/mempool/addresses/{address}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/metadata/txs/labels/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/metadata/txs/labels/{label}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/schemas/txs/tx_metadata_label_json.yaml:
  spec:
    - "#/items/properties/json_metadata/nullable"
src/paths/api/metadata/txs/labels/{label}/cbor.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/extended.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/total.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/utxos/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/utxos/{asset}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/txs.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/addresses/{address}/transactions.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/extended.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/retired.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/retiring.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/history.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/metadata.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/relays.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/delegators.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/blocks.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/pools/{pool_id}/updates.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/{asset}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/{asset}/history.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/{asset}/txs.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/{asset}/transactions.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/{asset}/addresses.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/assets/policy/{policy_id}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/{script_hash}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/{script_hash}/json.yaml:
  operation-operationId:
    - "#/get/operationId"
src/schemas/scripts/script_json.yaml:
  spec:
    - "#/properties/json/nullable"
src/paths/api/scripts/{script_hash}/cbor.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/{script_hash}/redeemers.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/datum/{datum_hash}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/scripts/datum/{datum_hash}/cbor.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/utils/addresses/xpub/{xpub}/{role}/{index}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/utils/txs/evaluate/index.yaml:
  operation-operationId:
    - "#/post/operationId"
src/paths/api/utils/txs/evaluate/utxos.yaml:
  operation-operationId:
    - "#/post/operationId"
src/paths/ipfs/gateway/{IPFS_path}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/ipfs/pin/add/{IPFS_path}/index.yaml:
  operation-operationId:
    - "#/post/operationId"
src/paths/ipfs/pin/list/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/ipfs/pin/list/{IPFS_path}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/ipfs/pin/remove/{IPFS_path}/index.yaml:
  operation-operationId:
    - "#/post/operationId"
src/paths/api/metrics/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/metrics/endpoints.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/network/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/network/eras.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/nutlink/{address}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/nutlink/{address}/tickers/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/nutlink/{address}/tickers/{ticker}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
src/paths/api/nutlink/tickers/{ticker}/index.yaml:
  operation-operationId:
    - "#/get/operationId"
